version: "3.8"

services:
  broker:
    image: redis
    restart: unless-stopped
    networks:
      - default

  db:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
    networks:
      - default

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - "8899:8000"
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_DBNAME: paperless
      PAPERLESS_DBUSER: paperless
      PAPERLESS_DBPASS: paperless
      PAPERLESS_PORT: 8000
      PAPERLESS_BIND_ADDR: 0.0.0.0
    volumes:
      - ./data:/usr/src/paperless/data
    networks:
      - default

networks:
  default:
    driver: bridge
